### get all
GET http://localhost:3000/api/genres
Accept: application/json

### get all sorted
GET http://localhost:3000/api/genres?sortBy=name
Accept: application/json

### get one
GET http://localhost:3000/api/genres/1
Accept: application/json

### post new genre
POST http://localhost:3000/api/genres
Content-Type: application/json

{
  "name": "action"
}

### update genre
PUT http://localhost:3000/api/genres/7
Content-Type: application/json

{
  "name": "porn"
}

### delete genre
DELETE http://localhost:3000/api/genres/7
